language: elixir

matrix:
  include:
    - otp_release: 17.5
      elixir: 1.1.1
    - otp_release: 19.2
      elixir: 1.4.0
    - otp_release: 20.0
      elixir: 1.5.2

sudo: false

script: mix test --no-start --trace
